name = "nexdrak-admin"
pages_build_output_dir = ".open-next/assets"
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

# We use OpenNext to bundle as Cloudflare Pages worker.
# Personalization: use separate zone + custom domain: "admin.nexdrak.com".
